services:
  web:
    depends_on:
      - db
    command: python app.py
    build: .
    ports:
      - "10000:10000"  # Flask app port
    env_file:
      - .env
    

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty1234
      MYSQL_DATABASE: hostel_db
    ports:
      - "3308:3306"  # Changed from 3307 to 3308
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
